# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test-Tequila-Chemistry

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: madness basics
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -e .
        cd tests
        ls
        pytest test_chemistry_madness.py
        cd ../
#    - name: Install and test Psi4 interface
#      run: |
#        ver=$(python -c"import sys; print(sys.version_info.minor)")
#        fullver=$(echo "3.$ver")
#        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
#        export CONDABASE=$HOME/miniconda
#        bash miniconda.sh -b -p $CONDABASE
#        export PATH=$CONDABASE:$PATH
#        export PATH="$CONDABASE/bin:$PATH"
#        conda update -q conda
#        conda create -n test_psi4 python=$fullver
#        conda init bash
#        bash
#        source $HOME/.bashrc
#        source $CONDABASE/bin/activate
#        conda activate test_psi4
#        conda install psi4 -c psi4
#        python -m pip install --upgrade pip
#        python -m pip install -r requirements.txt
#        python -m pip install -e .
#        cd tests
#        ls
#        pytest test_chemistry_madness.py
#        pytest test_chemistry.py
#        cd ../
    - name: Install and test madness interface
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
        echo "trying to install mkl ..." 
        sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
        sudo apt-get update
        sudo apt-get install -y intel-mkl-64bit-2020.1-102
        
        sudo apt-get install -y mpich

        wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2
        tar --bzip2 -xf boost_1_73_0.tar.bz2

        git clone https://github.com/dpilger26/NumCpp.git numcpp
      
        git clone https://github.com/kottmanj/madness.git madsrc

        mkdir madroot
        base=$(pwd)
        cd madroot
        cmake -D ENABLE_MKL=ON -D MKL_ROOT_DIR=/opt/intel/compilers_and_libraries_2020.1.102/linux/mkl -D CMAKE_CXX_FLAGS='-O3 -DNDEBUG -march=native -I/${base}/numcpp/include/ -I/${base}/boost_1_73_0/'  ${base}/madsrc/
        make -j
        export MAD_ROOT_DIR=$(pwd)
        cd $base

        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -e .
        cd tests
        pytest test_chemistry_madness.py
        cd ../


